Added error handling for scrollIntoView (fix for #1365)
mui-org/material-ui-pickers pull request #1366
Opened 2019-10-26 16:54 UTC by patorjk

This PR closes https://github.com/mui-org/material-ui-pickers/issues/1365

## Description

Added error handling for the scrollIntoView method, which errors in Firefox versions before 58 (according to the [Material UI docs](https://material-ui.com/getting-started/supported-platforms/) Firefox versions >= 52 are supported).

How to test this:

* Download and use Firefox v52: https://ftp.mozilla.org/pub/firefox/releases/
* Go here to see the error: https://material-ui-pickers.dev/demo/datepicker

You'll see it gives a white screen, look in the console to see the ScrollIntoView error message.

In this PR, do the same thing except go here: http://localhost:3000/demo/datepicker - no error occurs. Open a DatePicker and click the Year. See that you can select a year just fine.

2019-10-26 18:04 UTC, dmtrKovalenko requested changes
I think in this case we need just do nothing. If there is no window.scrollIntoView.

`if (!window.scrollIntoView)` 
Because try {} catch (e) can make some performance degradation for server side rendering apps

2019-10-26 19:27 UTC, patorjk commented
That test unfortunately won't work. Firefox versions 52 through 57 have a scrollIntoView method, it just doesn't work correctly. It will throw an error for inputs of "nearest" or "center" to the block property:

`TypeError: 'block' member of ScrollIntoViewOptions 'center' is not a valid value for enumeration ScrollLogicalPosition.`

2019-10-27 23:52 UTC, patorjk commented
Also, I'm totally open to changing this to work without the try/catch block, I'm just not sure how to detect the problem with "center" and "nearest" not being apart of ScrollLogicalPosition. I tried to see if I could find the enumeration via code, but wasn't able to. Another possible fix could be checking if the browser is Firefox and the version is less than 58, since this problem appears to be scoped to that Browser incorrectly implementing scrollIntoView.

2019-11-15 12:37 UTC, dmtrKovalenko commented
Closed in favor of #1393

2019-11-15 12:37 UTC, closed without merging

2019-11-15 13:12 UTC, patorjk commented
While I’m happy you’re moving forward with a fix, it looks like the only difference between that PR and this one is that you’ve removed what happens in the catch statement. That means FF users 50-57 will see 1800 as their date to select and have to manually scroll to the middle to select their date.