[docs] Update date-fns example
mui-org/material-ui-pickers pull request #1397
Opened 2019-11-19 20:40 UTC by Doesntmeananything

## Description

I would like to expand date-fns example in the docs with some approaches to customise formatting when date-fns locale object defaults are not appropriate. Since date-fns is very often used for localisation, I believe this is a natural place for more customisation examples. I have also added a link to format customisation guide to this page.

My friend and I were recently bitten by this. She was implementing a picker in tandem with date-fns, and the months were declined incorrectly for that particular case. Since the issue concerned a particular locale, googling around didn't really help. I then decided to review the docs again and managed to stumble upon Global format customisation guide after quite a bit of digging.

I have also added grammar and style fixes to some of the pages that I had time to  review.

Thank you very much!

2019-11-19 21:03 UTC, dmtrKovalenko requested changes
Overall thank you, this is a really good addition. 
But, please create a new section with heavily customized example. It will make easier to understand what is required

2019-11-20 19:09 UTC, Doesntmeananything commented
Something like this? I've added a new section to the date-fns page and moved customised example to a separate file.

2019-11-21 11:28 UTC, dmtrKovalenko requested changes

2019-11-21 11:28 UTC, dmtrKovalenko commented on docs/pages/localization/Date-fns-customized.example.jsx
> +  ru: 'd MMMM yyyy',
```suggestion
  ru: 'd MMM yyyy',
```

I think it was not expected 
![image](https://user-images.githubusercontent.com/16926049/69334158-ca627580-0c62-11ea-87a1-c81d68d934e4.png)

2019-11-21 11:29 UTC, dmtrKovalenko commented
I am sorry but I cannot push to your fork. Please commit the suggestion

2019-11-21 11:32 UTC, dmtrKovalenko commented on docs/pages/localization/Date-fns-customized.example.jsx
> +  ru: 'd MMMM yyyy',
BTW I would expect чет, `21 ноября` or just `21 ноября` in the header title as a Russian speaker. But it is just like an enhancement

2019-11-21 17:34 UTC, Doesntmeananything commented
No problem! I don't think particular formatting is a big deal here for me, since I'd rather concentrate on showcasing various custmomisation options for the pickers. I wouldn't want people hacking on date-fns before trying these out.

Made both suggested changes.

2019-11-21 20:09 UTC, dmtrKovalenko approved these changes
Thanks, it looks awesome right now. And really show that we need more developer friendlier way to change formatting for all of inner date renders.

2019-11-21 20:09 UTC, merged