fix ts error in overrides.ts
mui-org/material-ui-pickers pull request #1533
Opened 2020-02-23 19:43 UTC by hamza0867

fixes #1510

This PR closes #1510 

## Description
There is an issue right now with using the overrides method suggested in the [docs](https://material-ui-pickers.dev/guides/css-overrides#typescript).
You can find more details in the description of the issue #1510 

This PR intends to fix that issue.

2020-02-24 08:42 UTC, dmtrKovalenko requested changes
I cannot understand how requiring all keys can help here. But anyway please firstly fix CI errors

2020-02-24 08:46 UTC, hamza0867 commented
Well this is weird, because my PR builds on my machine without any issues
![Screenshot from 2020-02-24 09-45-53](https://user-images.githubusercontent.com/38878982/75138435-7d22f380-56ea-11ea-827d-46b0aa8445d2.png)

2020-02-24 10:37 UTC, hamza0867 commented
If you take a look at the material-ui overrides.d.ts you will find that all the members of ComponentNameToClassKey are required [here](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/styles/overrides.d.ts#L104), so the conflict is that the material-ui pickers are optional (can be undefined) while the originals cannot, that's why we get the error: 
```bash
node_modules/@material-ui/core/styles/overrides.d.ts:101:64 - error TS2344: Type 'ComponentNameToClassKey[Name]' does not satisfy the constraint 'string'.
  Type '"fixed" | "required" | "rtl" | "square" | "active" | "disabled" | "track" | "default" | "error" | "progress" | "message" | "middle" | "media" | "hidden" | "body" | "button" | "caption" | ... 400 more ... | undefined' is not assignable to type 'string'.
    Type 'undefined' is not assignable to type 'string'.

101   [Name in keyof ComponentNameToClassKey]?: Partial<StyleRules<ComponentNameToClassKey[Name]>>
                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

What I did in my project is change the material-ui pickers overrides.d.ts to match what I did in this PR and I could build the project.

I also just tried to build the docs (the step where the CI failed) from a clean copy of material-ui pickers on branch v3-x and it still fails (without me changing anything). So I do not believe the changes I made are the cause why the CI fails.

Thank you so much for your help

2020-03-03 12:20 UTC, dmtrKovalenko commented
Closing PR due to inactivity

2020-03-03 12:20 UTC, closed without merging