Add prop to render elements after calendar (#1795)
mui-org/material-ui-pickers pull request #1945
Opened 2020-06-29 16:18 UTC by Jenselme

This allows us to render anything after the calendar (buttons, text…)
by passing the renderCalendarInfo props to DateRangePicker.

- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).

Right now this PR is missing tests and documentation for the new props.

Before doing that, I'd like some inputs from you to see whether my approach seems correct to you. I'd also like to update the `DatePicker` to provide similar functionnality if it is. I tried to follow the ideas discussed in the related issue #1795 

My interogation is: I am rendering the extra information at the right place (after the `Calendar` component) or should I render it inside the `Calendar` component.

2020-06-29 20:09 UTC, dmtrKovalenko requested changes

2020-06-29 20:09 UTC, dmtrKovalenko commented on lib/src/DateRangePicker/DateRangePickerViewDesktop.tsx
> +  renderCalendarInfo?: React.ReactNode;
Will be better to have a function that will take the currentMonth as an argument.

2020-06-29 21:05 UTC, oliviertassinari commented
This concern is quite interesting. I think that we can use it as a case study, also with #1907 around how we can improve the customization API. I would propose we keep this pull request on hold until we resolve https://github.com/mui-org/material-ui/issues/21453.

I went a bit looking into react-day-picker and found a `components` API https://react-day-picker-next.netlify.app/docs/custom-components. It looks heavily inspired by https://react-select.com/components.

2020-06-30 09:20 UTC, Jenselme commented
> I went a bit looking into react-day-picker and found a components API https://react-day-picker-next.netlify.app/docs/custom-components. It looks heavily inspired by https://react-select.com/components.

Do you think the `components` API is more the way to go than the function?

I haven't seen https://github.com/mui-org/material-ui/issues/21453 before creating this but yes, a uniform API would be better. Let me know if I can help. Currently, I'll have to use a custom build of the project to move forward with my project, but I'd like to see this go upstream as fast as possible. Perhaps we can also move forward with the function right now and change it in a new version (if I understand correctly version 4 is still in alpha so we can do this).

2020-06-30 09:44 UTC, oliviertassinari commented
> Perhaps we can also move forward with the function right now and change it in a new version (if I understand correctly version 4 is still in alpha so we can do this).

@Jenselme Sorry, this is not possible, we would only merge changes once we are confident we have explored enough the alternative options.

2020-07-01 13:42 UTC, dmtrKovalenko commented
In my opinion render function here will be the best choice. Because it will be possible to render it dynamically for months without having to introduce new state. 

My idea: 

```
<DatePicker 
   renderCalendarInfo={(month) => <div> You will not be able to do something before {moth.sub({ month: 1 })} </div>
/>
```

Moreover we need to handle it for DateRangePicker where it is extremely useful. Something like


```
<DateRangePicker 
   renderLastCalendarInfo={(month) => <Button> I do not need return ticket </Button>} 
/>
```

It is the most required functionality I suppose

2020-07-01 14:50 UTC, Jenselme commented
@dmtrKovalenko so with two functions, one to allow rendering before the calendar and one to allow rendering after?

2020-07-01 16:45 UTC, oliviertassinari commented
What about this approach? This configuration can reduce the need for new custom APIs, we can reuse the existing component separation of the internal, progressively expose more

```tsx
import { DateRangePicker, Calendar } from '@material-ui/pickers';

function MyCalendar(props) {
  return <Calendar {...props} />;
}

return (
  <DateRangePicker components={{ MyCalendar }} />
);
```

2020-07-02 13:00 UTC, dmtrKovalenko commented
I am not sure, will it be "over" customized? 
There is the point when customization ability becomes a pain. Here as for me render function will fit the best

2020-07-03 11:18 UTC, oliviertassinari commented
@dmtrKovalenko I think that in an ideal world, we would expose an API that allows composition, the closer we are to the DOM notes, the better.

```jsx
<DatePicker>
  <DatePickerInput />
  <DatePickerPopup>
    <Calendar />
  </DatePickerPopup>
<DatePicker>
```

Now, in practice, this is likely overkill, it requires a lot of coordination.

I think that we can benefit from your existing reflection on what's the best wait to separate the different components and simply reexpose them. I have added a couple of more thoughts on the problem on https://github.com/mui-org/material-ui/issues/21453#issuecomment-653496935

2020-07-03 11:20 UTC, oliviertassinari commented
> I am not sure, will it be "over" customized?
There is the point when customization ability becomes a pain. Here as for me render function will fit the best

I think that over-customizability is a concern on its own and that can be resolved independently. No matter the direction we go in.

2020-08-31 09:55 UTC, Jenselme commented
@oliviertassinari @dmtrKovalenko did you decide for a path forward? I'd really like to complete this and see it merged in September ;-)

2020-08-31 11:00 UTC, oliviertassinari commented
@Jenselme Yes, we would be going with https://github.com/mui-org/material-ui/issues/21453#issuecomment-657278080 the conclusion of. However, we might still change the names of these props. `slotComponents` could become `components` and `slotProps` -> `componentsProps`.

2020-08-31 12:16 UTC, Jenselme commented
@oliviertassinari any idea when this will be stable?

2020-08-31 12:22 UTC, oliviertassinari commented
@Jenselme What would be stable? The name? The name can be changed later on, it's a low-cost change, no need to optimize for it.

2020-08-31 12:27 UTC, Jenselme commented
> The name can be changed later on, it's a low-cost change, no need to optimize for it.

If it's just the names, I can update this PR yes.

2020-08-31 13:01 UTC, oliviertassinari commented
@Jenselme Also, please mind this comment: https://github.com/mui-org/material-ui-pickers/pull/2092#issuecomment-679342233.

2020-09-07 15:33 UTC, Jenselme commented
@oliviertassinari if I understood correctly, it should be something like this: https://github.com/mui-org/material-ui-pickers/pull/1945/commits/4b82dd04070574de3aca48cdb9e862f6ce52057d Am I right?

2020-09-07 15:40 UTC, oliviertassinari commented
Yes, it looks close :)

2020-09-08 15:18 UTC, Jenselme commented
I just updated the PR, that should be it. I'm not used to TS so I may have done mistakes with it. I know I had to add a `// @ts-ignore` in my example.

For testing, should I use "calendar customization" in `docs/pages/regression/Regression.tsx` to validate this?

I also noted that this PR won't be merged directly because of https://github.com/mui-org/material-ui/issues/21453#issuecomment-657278080 But I think the result is reviewable anyway.

2020-11-22 10:45 UTC, oliviertassinari commented
@Jenselme Thanks for working on the problem. I'm closing as we have moved the component to https://github.com/mui-org/material-ui.

2020-11-22 10:45 UTC, closed without merging